::nvcc -o main.exe main.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o sinPhase.exe sinPhase.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o hexPhase.exe hexPhase.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o cosSphere.exe cosSphere.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o cosCyl.exe cosCyl.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o spec_vs_simp1.exe spec_vs_simp1.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o spec1_vs_simp.exe spec1_vs_simp.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o WCcompare.exe WCcompare.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o magLF.exe magLF.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o magLF_spherNeuman.exe magLF_spherNeuman.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o magHF_spherNeuman.exe magHF_spherNeuman.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o cosSphere_LF.exe cosSphere_LF.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o planePhase.exe planePhase.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o hexPhase_diam.exe hexPhase_diam.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o multigpu.exe multigpu.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff 
::-use_fast_math
::nvcc -o magLF_pgse.exe magLF_pgse.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o gammadist.exe gammadist.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::nvcc -o magLF_UCN.cu.exe magLF_UCN.cu -m 32 -arch sm_20 -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" -o cosOneCyl.exe Cos_OneCyl.cu --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" -o cosOneSphere1reg.exe Cos_OneSphere1reg.cu --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" -o cosOneSphere2reg.exe Cos_OneSphere2reg.cu --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" -o gammadist.exe gammadist.cu --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" -o printRadii.exe printRadii.cu --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" -o sinOneSphere1reg_mel.exe Sin_OneSphere1reg_mel.cu --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff

"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o magLF_UCN.exe magLF_UCN.cu -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o SW_OneCyl.exe SW_OneCyl.cu -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o Cos_OneCyl.exe Cos_OneCyl.cu -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o gammadistCos.exe gammadistCos.cu -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o gammadistSW.exe gammadistSW.cu -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o sinOneSphere1reg_mel.exe Sin_OneSphere1reg_mel.cu -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
::"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o cosOneSphere1reg_mel.exe Cos_OneSphere1reg_mel.cu -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o acosOneSphere1reg_mel.exe ACos_OneSphere1reg_mel.cu -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o AcosEmptyMel.exe Acos_Empty_Mel.cu -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\vcvars32.bat" && "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\bin\nvcc.exe" --use-local-env --cl-version 2010 -ccbin "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin" --machine 32 -arch sm_20 -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -o WCcompareRAW.exe WCcompareRAW.cu -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v5.5\include" -I ./acquisition -I ./functors -I ./kernels -I ./params -I ./primitives -I ./substrate -I ./util -I ./blochdiff -use_fast_math 2> errors.txt

SW_OneCyl > SW_OneCyl_aug18_12AM.txt
Cos_OneCyl > Cos_OneCyl_aug18_12AM.txt
gammadistCos > gammadistCos_aug18_12AM.txt
gammadistSW > gammadistSW_aug18_12AM.txt
magLF_UCN > magLF_UCN_aug18_12AM.txt





